# Generated by Django 3.2.8 on 2021-10-23 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileCreated', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('brother', 'Brother'), ('sister', 'Sister')], default='self', max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=225)),
                ('community', models.CharField(max_length=225)),
                ('moblie', models.CharField(max_length=225)),
                ('preferredProfile', models.CharField(max_length=225)),
                ('dateOfBirth', models.DateField()),
                ('relegion', models.CharField(max_length=225)),
                ('nationality', models.CharField(max_length=225)),
                ('height', models.CharField(max_length=225)),
                ('weight', models.CharField(max_length=225)),
                ('martialStatus', models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced')], default='single', max_length=225)),
                ('complexion', models.CharField(max_length=225)),
                ('ethnicGroup', models.CharField(max_length=225)),
                ('bodyType', models.CharField(choices=[('slim', 'Slim'), ('muscular', 'Muscular'), ('fat', 'Fat')], default='slim', max_length=225)),
                ('physicalStatus', models.CharField(max_length=225)),
                ('motherTongue', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': 'UserProperties',
            },
        ),
        migrations.CreateModel(
            name='UserEducationLocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highestEducation', models.CharField(max_length=225)),
                ('profession', models.CharField(max_length=225)),
                ('professionType', models.CharField(max_length=225)),
                ('nativeCountry', models.CharField(max_length=225)),
                ('nativeState', models.CharField(max_length=225)),
                ('nativeCity', models.CharField(max_length=225)),
                ('primaryNumber', models.CharField(max_length=225)),
                ('secondaryNumber', models.CharField(max_length=225)),
                ('preferedContact', models.CharField(max_length=225)),
                ('relation', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Profile/', verbose_name='Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
