# Generated by Django 3.2.8 on 2021-10-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userproperties_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usereducationlocationcontact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userproperties'),
            preserve_default=False,
        ),
    ]
